### ISSUE TITLE
Question about pyproject.toml syntax

### ISSUE THREAD

**Issue by adamjstewart** [jupyter/jupyter-packaging#120]
The README for this project suggests using:
```toml
[build-system]
requires = ["jupyter_packaging~=0.10.0,<2"]
build-backend = "setuptools.build_meta"
```
However, doesn't `~=0.10.0` imply `>=0.10.0,==0.10.*`? So not only is the `<2` unnecessary, it's also misleading since it suggests that version 0.11.0 or 1.X would work? I'm referring to [this syntax specification](https://www.python.org/dev/peps/pep-0440/#compatible-release).
